# Generated by Django 3.2.9 on 2021-12-06 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_recepient_message_recipient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-created']},
        ),
    ]
